### ISSUE TITLE
QUESTION: Multiple collections and homepage

### ISSUE THREAD

**Issue by DmytroLitvinov** [royalfig/smart#276]
Hi Ryan,
I am trying to set up  two main collections of content, like /blog/ and /til/

I followed https://ghost.org/docs/themes/routing/ and I provided the next custom `routes.yaml`:

```
routes:
  /: home

collections:
  /blog/:
    permalink: /blog/{slug}/
    template: index
    filter: 'tag:hash-blog'
  /til/:
    permalink: /til/{slug}/
    template: index
    filter: 'tag:hash-til'

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
```

When I restarted webserver at [my website](https://dmytrolitvinov.com), it shows me 400 error:
<img width="1349" alt="image" src="https://user-images.githubusercontent.com/16066485/224567806-9c00b569-e36e-468f-b756-f522eb25a4a0.png">

**Comment by DmytroLitvinov** [comment]
I suppose I am doing something wrong in `routes.yaml` in my case.

**Comment by DmytroLitvinov** [comment]
After a lot of tries and better reading documentation of Ghost, I found solution:

```
routes:
  /:
    template: home
    controller: channel
    filter: "tag:hash-blog"

collections:
  /blog/:
    permalink: /blog/{slug}/
    template: index
    filter: 'tag:hash-blog'
  /til/:
    permalink: /til/{slug}/
    template: index
    filter: 'tag:hash-til'

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
```

Where on homepage I will show only posts from my blog.
