### ISSUE TITLE
FEATURE REQUEST: Microblogging template

### ISSUE THREAD

**Issue by DmytroLitvinov** [royalfig/smart#277]
Hi Ryan.

Can we create "archive" template tag like https://godofredo.ninja/archive/ or https://zenhabits.net/archives/ but more in a microblogging way?

Let me a bit describe my context and how I am gonna use it:
I would like to start a new section like "TIL" (which stands for Today I Learned) where I will post short posts in 1-3 sentences. Like micro-blogging. The idea of "TIL" content type is pretty good described [here](https://hynek.me/articles/til/).

Other examples of TIL sections:
* https://michaelheap.com/til/ (I like the way tags are used here) 
* https://til.unessa.net/
* https://hynek.me/til/ (I like that this is like a list of rows) 
* https://til.simonwillison.net/ (and then there is "all" page - https://til.simonwillison.net/all) We can see posts are grouped by tag also.

*So how do I see it in the end:*
It should be a list of rows with title and except shown like in https://hynek.me/til/ and date of publication (should be in lowercase).
Definitely tags should be used for quicker navigation. 

Let me know what do you think and if it possible to do?

**Comment by DmytroLitvinov** [comment]
Great! Thank you for your response 👍 

I am eagerly looking forward to custom page template with a list of "microposts".

**Comment by royalfig** [comment]
A TIL custom template has been included in v2.5.0 🥳 

Here's how to use it:
1. Create a new page
2. In the sidebar, choose the `Til` template
3. Internally tag posts that you want to show up on this page with the slug of the new page you created. For example, if you called the page TIL, you'd tag the posts `#til`. If you called the page, "Stuff I learned," then you'd tag the page `#stuff-i-learned`. 
4. Publish the page!

**Comment by DmytroLitvinov** [comment]
Hi @royalfig ,
You rock!

That how I did before releasing that new template 👍 
Here is my [TIL page](https://dmytrolitvinov.com/til/) and here is an [example](https://dmytrolitvinov.com/til/requests-timeouts/) of it using "Til" template.

The only nitpick: can we rename the template name to "TIL" instead of "Til"? Like to make it as abbreviation? 
<img width="1348" alt="image" src="https://user-images.githubusercontent.com/16066485/229306607-ef444a50-f5ba-43bf-9a96-630acbabeedd.png">

**Comment by royalfig** [comment]
Good call. Updated!

Redownload the release or repo...

**Comment by royalfig** [comment]
![image](https://user-images.githubusercontent.com/48868107/229307354-8ac332bf-7c00-4f68-974d-bac01b6a16c3.png)
 

Here's also what it should look when enabled...

**Comment by DmytroLitvinov** [comment]
Should I adapt `content/settings/routes.yaml` file for `/til/` collections?

```
routes:
  /:
    template: home
    controller: channel
    filter: "tag:hash-blog"

collections:
  /blog/:
    permalink: /blog/{slug}/
    template: index
    filter: 'tag:hash-blog'
  /til/:
    permalink: /til/{slug}/
    template: index
    filter: 'tag:hash-til'

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
```

**Comment by DmytroLitvinov** [comment]
Ah... Sorry. I did not follow instructions. You said we need to create a new Page instance and I did it with routes.

**Comment by DmytroLitvinov** [comment]
@royalfig , followed instructions:

1. Created a new Page with slug "til"
<img width="1348" alt="image" src="https://user-images.githubusercontent.com/16066485/229309225-620ff2df-bb68-47d6-afd5-eb221b1fef07.png">
<img width="1352" alt="image" src="https://user-images.githubusercontent.com/16066485/229309231-84e05c39-49b5-4d22-a8d9-e3ef8d739a32.png">
2. Created new tag with hash (internal tag) - "hash-til" where mask is `hash-{slug of created page}`
<img width="1349" alt="image" src="https://user-images.githubusercontent.com/16066485/229309295-65b29a6c-ca8e-4bed-b6c8-e062e37abc04.png">
3. Added newly created on one of the published posts which will be used for microblogging with selection "TIL" in the sidebar for template
<img width="1350" alt="image" src="https://user-images.githubusercontent.com/16066485/229309347-e123b0bc-6c3b-4883-ae24-57c0fcb0ce43.png">
<img width="1349" alt="image" src="https://user-images.githubusercontent.com/16066485/229309387-c0a69237-2ae3-4c5f-a0ca-d9bf52ca664c.png">
4. Opened new TIL page - https://dmytrolitvinov.com/til/
5. UI right now is the same as in the comment but with next problems:
   5.1 If there is no additional tag on blog post, then empty space is visible
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/16066485/229309496-13c494b2-cc9b-4c1c-94fb-051d311f3023.png">
    5.2 The generated URL is not working correctly
    
<img width="1352" alt="image" src="https://user-images.githubusercontent.com/16066485/229309535-fa92f4b7-1d08-48c9-a6cb-0d6ae20d6363.png">

**Additional info:**
Here is routes.yaml file:
```
routes:
  /:
    template: home
    controller: channel
    filter: "tag:hash-blog"

collections:
  /blog/:
    permalink: /blog/{slug}/
    template: index
    filter: 'tag:hash-blog'
#  /til/:
#    permalink: /til/{slug}/
#    template: til-card
#    filter: 'tag:hash-til'
  /digest/:
    permalink: /digest/{slug}/
    template: index
    filter: 'tag:digest'
  /newsletter/:
    permalink: /newsletter/{slug}/
    filter: 'tag:hash-newsletter'

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
```

**Comment by royalfig** [comment]
Added a new release that corrects the primary tag and whitespace. v2.6.0

The problem with the URL is because of your routing setup. The major issue, I think, is that collections need to be mutually exclusive, which means excluding the other tags in your filter. See the docs on this: https://ghost.org/docs/faq/filter-property-routes-yaml/

Try, though, resetting your routing to the default. See if the URL works correctly. If so, then you know that the issue is with your routes. 

I think your main goal is to exclude certain posts from the homepage. Then, have pages for newsletter, til, etc. I think another approach would be to just to define the default route with the filter you want and then use the automatically created tag pages for the rest. If you don't want "tag" in the URL, then you can remove it as prefix in the taxonomies section.

**Comment by DmytroLitvinov** [comment]
Maybe let me start from scratch and it will help to better understand what I want to explain and have in the end.

I have a website on which I want to have two separate types of posts according to [URLs & Dynamic Routing](https://ghost.org/docs/themes/routing/) as "/blog/" and "/til/" (our microblogging new feature) _(In the docs it is under section **"When to use dynamic routing"**)_

<img width="832" alt="image" src="https://user-images.githubusercontent.com/16066485/229331270-5536f22c-9e49-4300-b0b8-dfc6011939d6.png">

For that case, I need to use dynamic routing and I provided next config for `routes.yaml`:
```
routes:
  /:
    template: home
    controller: channel
    filter: "tag:hash-blog"

collections:
  /blog/:
    permalink: /blog/{slug}/
    template: index
    filter: 'tag:hash-blog'
  /til/:
      permalink: /til/{slug}/
      filter: 'tag:hash-til'
```

Collection in that case is fine according to article:
<img width="846" alt="image" src="https://user-images.githubusercontent.com/16066485/229331428-7331c605-1e1a-4fb1-9315-5df40883ae2f.png">

So two types of posts are mutually exclusive using the internal tag like `hash-blog` and `hash-til`. But what it does not work in `/til/` (parent page of TIL type of posts) template - it is not the same as on [your comment](https://github.com/royalfig/smart/issues/277#issuecomment-1493063690). I am just recently started to use Ghost so I suppose we need to create a separate file for that like `til.hbs` structure of the file should be similar to [index.hbs](https://github.com/royalfig/smart/blob/main/index.hbs) and content for that file should be taken from [custom-TIL.hbs](https://github.com/royalfig/smart/blob/main/custom-TIL.hbs) so in the end template will look like:

```
{{!< default}}
{{!-- The tag above means: insert everything in this file
into the {body} of the default.hbs template --}}
{{> "header"}}

<main class="sm-header-grid sm-post-content sm-micro-header {{post_class}} {{slug}}" id="sm-main">
    {{content}}
</main>

<section class="sm-header-grid sm-micro-grid">
    {{#foreach posts}}
        {{> "til-card"}}
    {{/foreach}}
</section>
{{/if}}

{{/get}}

{{pagination}}
```

I just tested that setup locally and it works. 
<img width="1351" alt="image" src="https://user-images.githubusercontent.com/16066485/229332144-9f65e7f0-f5b7-40a7-86c6-5a990f21f6f1.png">

The only case which is not working in that example is dynamically provided text for `/til/` page from CMS. Ryan, if it is something we can do, I am glad to help you here like opening MR with corresponded changes. Solution is almost prepared, the only question is dynamic content via CMS where "undefined" in my screenshot.
