### ISSUE TITLE
FEATURE REQUEST: Pinned posts on homepage

### ISSUE THREAD

**Issue by DmytroLitvinov** [royalfig/smart#292]
Just looked and what already exists in Ghost themes and found https://github.com/lukencode/GhostSolo. I like the way of pinned posts on the homepage https://lukelowrey.com/ as author of website has. 

I think it would be nice to have it in the future. We can keep it with low priority in backlog.

**Comment by royalfig** [comment]
I think the best way to do this (for this theme) is via routing. 

In routes.yaml, you'd do this:

```yaml
routes:
  /:
  controller: channel
  order: featured desc, published_at desc
```

This pulls featured posts to the front of the list. The reason I like this approach is that it preserves the normal pagination of the Ghost site.

I'll close this for now, but I'll think about it in the future.
